version: "3.8"
services:
  gerenciador_dieta-production:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gerenciador_dieta-front
    ports:
      - 3000:3000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    working_dir: /usr/src/gerenciador_dieta
    command: npm run build
    environment:
      NODE_ENV: production
      REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
    volumes:
      - /usr/src/gerenciador_dieta/front-end:/usr/src/gerenciador_dieta/build
    command: npm run start